config/routes.rb
ShoppingManagement::Application.routes.draw do
  root :to => 'shopping_management_developments#menu'
  resources :shopping_management_developments #do
  post "shopping_management_developments/new"
  post "shopping_management_developments/searchInit"
  post "shopping_management_developments/search"
  post "shopping_management_developments/searchHistory"
  post "shopping_management_developments/createShohi"

  

end

app/models/shopping_management_development.rb
# coding:utf-8
class ShoppingManagementDevelopment < ActiveRecord::Base
  
#  attr_accessible :categoryCd,:goods,:amount,:sum,:place
  
  validates :categoryCd,
  :presence =>  { :message => "%{value}を入力してください" }
  validates :goods,
  :presence =>  { :message => "を入力してください" }
  validates :amount,
   :allow_nil => true,
   :numericality => { :greater_than_or_equal_to   => 0 ,:message => "は半角数字で入力してください"} , 
   :length => { :within => 0..6 ,:message => "は6文字以下で入力してください" } 
  validates :sum,
   :allow_nil => true,
   :numericality => { :greater_than => 0 ,:message => "は1以上で入力してください" ,
   :greater_than_or_equal_to   => 0,:message => "は半角数字で入力してください" } , 
   :length => { :within => 0..6 ,:message => "は6文字以下で入力してください" } 
  validates :place,
   :allow_nil => true,
   :length => { :within => 0..20 ,:message => "は20文字以下で入力してください" } 
    
end

app/controllers/shopping_management_developments_controller.rb
class ShoppingManagementDevelopmentsController < ApplicationController
  before_action :set_shopping_management_development, only: [:show, :edit, :update, :destroy]

#  def menu
#  end

  # 検索画面表示
  def searchInit
    @category = Category.find(:all)
    render :action => 'search.html.erb'
  end

  # 検索結果表示画面
  def search
    ## 検索画面からきたかどうかをparamsがNULLかどうかで切り分け
    if params[:goods].present?
    else
      #検索画面から渡ってきた条件をクラス変数に格納
      @categorytmp = params[:page]
      @@category = @categorytmp[:categorycd]
      
      @@goods = params[:goods]
    end

    #end
    
    # 検索条件 動的SQL作成
    # ～ 購入TBLと消費TBLから在庫数を算出する
    @sqlcode =
     "SELECT s.categoryCd , s.goods, buynum - shohinum as zaiko \
      FROM \
      ( \
       SELECT categoryCd, goods, SUM(sum) buynum \
       FROM shoppingmanagement_development.shopping_management_developments \
       WHERE categoryCd = ? AND goods like ? \
       GROUP BY categoryCd, goods \
      ) b ,\
      ( \
       SELECT categoryCd, goods, SUM(shohisum) shohinum \
       FROM shoppingmanagement_development.shohis \
       WHERE categoryCd = ? AND goods like ? \
       GROUP BY categoryCd, goods \
      ) s
      WHERE b.categoryCd = s.categoryCd
      AND   b.goods      = s.goods ;"


    puts "****************************************************"
    puts "カテゴリコード: #{@@category}"
    puts "商品名        : #{@@goods}"
    puts "SQL(bi mae)   : #{@sqlcode}"
    puts "****************************************************"

    #@sqlbind1 = "categoryCd = " 
    #@sqlbind2 = "goods      like "

    case
    when @@category.blank? && @@goods.blank?
        puts "ERROR: カテゴリ または 商品名 どちらかを入力して検索してください"
    when @@category.blank? || @@goods.blank?
      if @@category.blank?
           ## 商品名で検索 ##
           puts "カテゴリがNULLです"
           # カテゴリの条件を削除(置換)
           @sqlcode = @sqlcode.gsub("categoryCd = ? AND","")
           @results = ShoppingManagementDevelopment.find_by_sql([@sqlcode ,@@goods ,@@goods])
      elsif @@goods.blank?
           ## カテゴリで検索 ##
           puts "商品名がNULLです"
           @results = ShoppingManagementDevelopment.find_by_sql([@sqlcode , @@category ,"%", @@category ,"%"])
      end
    else 
      ## カテゴリ および 商品名で検索 ##
      puts "どちらもNULLでない"
           @results = ShoppingManagementDevelopment.find_by_sql([@sqlcode , @@category ,@@goods , @@category ,@@goods])
    end
    
    
    #@results = ShoppingManagementDevelopment.find_by_sql(["SELECT * FROM shopping_management_developments WHERE goods LIKE ? and categoryCd = ?", "%#{@@goods}%","#{@@category}"])

     ## 想定SQL
     # SELECT s.categoryCd , s.goods, buynum - shohinum as zaiko
     # FROM
     # (
     #  SELECT categoryCd, goods, SUM(sum) buynum
     #  FROM shoppingmanagement_development.shopping_management_developments
     #  WHERE categoryCd = :categorycode 
     #    AND goods like :goods
     #  GROUP BY categoryCd, goods
     # ) b,
     # (
     #  SELECT categoryCd, goods, SUM(shohisum) shohinum
     #  FROM shoppingmanagement_development.shohis
     #  WHERE categoryCd = :categorycode 
     #    AND goods like = :goods
     #  GROUP BY categoryCd, goods
     # ) s
     # WHERE b.categoryCd = s.categoryCd
     # AND   b.goods      = s.goods ;"

    render :action => 'searchResult.html.erb'
     
  end

  def createShohi
    time = Time.now
    puts "####################createshohi###################"
    puts "カテゴリ   : #{params[:category]}"
    puts "商品名     : #{params[:goods]}"
    puts "消費入力数 : #{params[:shohi]}"
    puts time
    puts "検索条件(カテゴリ) : #{@@category}"
    puts "検索条件(商品名)   : #{@@goods}"
    puts "####################createshohi###################"
    
    @shohimodel = Shohi.new(:categoryCd => params[:category] , :goods => params[:goods] , :shohiSum => params[:shohi] , :shohiDate => time )
    if @shohimodel.save
      puts "消費数を反映しました"
    else
      puts "処理に失敗しました"
    end
    
    #render :text => '更新しました' #, :action => 'searchResult.html.erb'
    search()
  end

  # 購入履歴一覧画面表示
  def searchHistory
   puts "####################searchHistory###################"
   puts "カテゴリ: #{params[:category]}"
   puts "商品名  : #{params[:goods]}"
   puts "####################searchHistory###################"

#テスト用Dummy
#    @shopping_management_developments = ShoppingManagementDevelopment.all
#    @history =  ActiveRecord::Base.connection.select("SELECT goods AS viewGoods, place AS viewPlace, 'test' AS viewStatus FROM shopping_management_developments")

    @sqlcode =
    "SELECT TMP.id, TMP.categoryCd, C.categoryname, TMP.viewGoods, TMP.viewDate, TMP.viewAmount, TMP.viewSum, TMP.viewPlace, TMP.viewStatus, '' AS delSt \
     FROM \
     ( SELECT A.id, A.categoryCd, A.goods AS viewGoods, A. DATE AS viewDate, A.amount AS viewAmount, A. SUM AS viewSum, A.place AS viewPlace, '購入' AS viewStatus \
       FROM shopping_management_developments A \
       WHERE A.categoryCd = ? AND A.goods = ? \
         UNION \
       SELECT B.id, B.categoryCd, B.goods, B.shohiDate AS viewDate, '' AS viewAmount, B.shohiSum AS viewSum, '' AS viewPlace, '消費' AS viewStatus \
       FROM shohis B WHERE B.categoryCd = ? AND B.goods = ? \
     ) TMP \
     INNER JOIN categories C ON (TMP.categoryCd = C.categorycd) ORDER BY TMP.viewDate desc;"

    @history = ShoppingManagementDevelopment.find_by_sql([@sqlcode, "#{params[:category]}", "#{params[:goods]}", "#{params[:category]}", "#{params[:goods]}"])

#     @history =  ActiveRecord::Base.connection.select("SELECT TMP.id,TMP.categoryCd,C.categoryname,TMP.viewGoods,TMP.viewDate,TMP.viewAmount,TMP.viewSum,TMP.viewPlace,TMP.viewStatus,'' AS delSt FROM (SELECT A.id,A.categoryCd,A.goods AS viewGoods,A. DATE AS viewDate,A.amount AS viewAmount,A. SUM AS viewSum,A.place AS viewPlace,'購入' AS viewStatus FROM shopping_management_developments A WHERE A.categoryCd = '1001' AND A.goods ='雑貨１' UNION SELECT B.id,B.categoryCd,B.goods,B.shohiDate AS viewDate,'' AS viewAmount,B.shohiSum AS viewSum,'' AS viewPlace,'消費' AS viewStatus FROM shohis B WHERE B.categoryCd = '1001' AND B.goods = '雑貨１') TMP INNER JOIN categories C ON (TMP.categoryCd = C.categorycd) ORDER BY TMP.viewDate desc")
#       SELECT
#        TMP.id
#        ,TMP.categoryCd
#        ,C.categoryname
#        ,TMP.viewGoods
#        ,TMP.viewDate
#        ,TMP.viewAmount
#        ,TMP.viewSum
#        ,TMP.viewPlace
#        ,TMP.viewStatus
#    FROM
#    (
#      SELECT
#          A.id
#          ,A.categoryCd
#          ,A.goods AS viewGoods
#          ,A. DATE AS viewDate
#          ,A.amount AS viewAmount
#          ,A. SUM AS viewSum
#          ,A.place AS viewPlace
#          ,'購入' AS viewStatus
#        FROM
#          shopping_management_developments A
#        WHERE
#          A.categoryCd = '1001'
#          AND A.goods = '雑貨１'
#      UNION
#      SELECT
#          B.id
#          ,B.categoryCd
#          ,B.goods
#          ,B.shohiDate AS viewDate
#          ,'' AS viewAmount
#          ,B.shohiSum AS viewSum
#          ,'' AS viewPlace
#          ,'消費' AS viewStatus
#        FROM
#          shohis B
#        WHERE
#          B.categoryCd = '1001'
#          AND B.goods = '雑貨１'
#    ) TMP INNER JOIN categories C ON (
#      TMP.categoryCd = C.categorycd
#    )
#    ORDER BY
#      TMP.viewDate
#    ")

    render :action => 'history.html.erb'
  end


  # GET /shopping_management_developments
  # GET /shopping_management_developments.json
  def index
    @shopping_management_developments = ShoppingManagementDevelopment.all
  end

  # GET /shopping_management_developments/1
  # GET /shopping_management_developments/1.json
  def show
  end

  # GET /shopping_management_developments/new
  def new
    @shopping_management_development = ShoppingManagementDevelopment.new
  end

  # GET /shopping_management_developments/1/edit
  def edit
  end

  # POST /shopping_management_developments
  # POST /shopping_management_developments.json
  def create
    # newでインスタンスを作成
    @shopping_management_development = ShoppingManagementDevelopment.new(shopping_management_development_params)

    respond_to do |format|
      if @shopping_management_development.save
        format.html { redirect_to @shopping_management_development, notice: 'Shopping management development was successfully created.' }
        format.json { render action: 'show', status: :created, location: @shopping_management_development }
      else
        format.html { render action: 'new' }
        format.json { render json: @shopping_management_development.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /shopping_management_developments/1
  # PATCH/PUT /shopping_management_developments/1.json
  def update
    respond_to do |format|
      if @shopping_management_development.update(shopping_management_development_params)
        format.html { redirect_to @shopping_management_development, notice: 'Shopping management development was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @shopping_management_development.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /shopping_management_developments/1
  # DELETE /shopping_management_developments/1.json
  def destroy
    @shopping_management_development.destroy
    respond_to do |format|
      format.html { redirect_to shopping_management_developments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shopping_management_development
      @shopping_management_development = ShoppingManagementDevelopment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shopping_management_development_params
      params.require(:shopping_management_development).permit(:categoryCd, :goods, :date, :amount, :sum, :place)
    end
end

app/helpers/shopping_management_developments_helper.rb
module ShoppingManagementDevelopmentsHelper
end

app/views/shopping_management_developments/_form.html.erb
<%= form_for(@shopping_management_development) do |f| %>
  <% if @shopping_management_development.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@shopping_management_development.errors.count, "error") %> prohibited this shopping_management_development from being saved:</h2>

      <ul>
      <% @shopping_management_development.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :categoryCd %><br>
    <%= f.number_field :categoryCd %>
  </div>
  <div class="field">
    <%= f.label :goods %><br>
    <%= f.text_field :goods %>
  </div>
  <div class="field">
    <%= f.label :date %><br>
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :amount %><br>
    <%= f.number_field :amount %>
  </div>
  <div class="field">
    <%= f.label :sum %><br>
    <%= f.number_field :sum %>
  </div>
  <div class="field">
    <%= f.label :place %><br>
    <%= f.text_field :place %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/shopping_management_developments/edit.html.erb
<h1>Editing shopping_management_development</h1>

<%= render 'form' %>

<%= link_to 'Show', @shopping_management_development %> |
<%= link_to 'Back', shopping_management_developments_path %>

app/views/shopping_management_developments/history.html.erb
<html>
<thead>
  <title>購入履歴一覧</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <%= stylesheet_link_tag 'ror' %>
</thead>

<tbody>
<h2>購入履歴一覧</h2>
<table border="1">
  <tr style="background-color:pink">
    <th>日付</th>
    <th>商品名</th>
    <th>個数</th>
    <th>金額</th>
    <th>購入場所</th>
    <th>状態</th>
    <th>削除</th>
    <th>更新</th>
  </tr>
  <% for r in @history %>
    <tr style="background-color:<%= cycle('white', 'yellow') %>">
      <td><%=  r.viewDate %></td>
      <td><%=h r.viewGoods %></td>
      <td><%=h r.viewSum %></td>
      <td><%=h r.viewAmount %></td>
      <td><%=h r.viewPlace %></td>
      <td><%=h r.viewStatus %></td>
      <td><%= check_box_tag :deleteflg, true, false, {} %></td>
          <%= hidden_field_tag 'session[:deleteflg] = :deleteflg' %>
      <td><%= link_to '更新', edit_shopping_management_development_path(r) %></td>
    </tr>
  <% end %>
</table>
<br><br>
<% form_tag({ :action => 'search' }) %>
<!-- link_to '戻る', shopping_management_developments_searchInit_path -->
<%= button_to  "戻る" , { :action => 'search' } %>
<br>
<%= link_to '購入商品在庫管理メニュー', root_path %>
</tbody>
</html>

app/views/shopping_management_developments/index.html.erb
<h1>Listing shopping_management_developments</h1>

<table>
  <thead>
    <tr>
      <th>Categorycd</th>
      <th>Goods</th>
      <th>Date</th>
      <th>Amount</th>
      <th>Sum</th>
      <th>Place</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @shopping_management_developments.each do |shopping_management_development| %>
      <tr>
        <td><%= shopping_management_development.categoryCd %></td>
        <td><%= shopping_management_development.goods %></td>
        <td><%= shopping_management_development.date %></td>
        <td><%= shopping_management_development.amount %></td>
        <td><%= shopping_management_development.sum %></td>
        <td><%= shopping_management_development.place %></td>
        <td><%= link_to 'Show', shopping_management_development %></td>
        <td><%= link_to 'Edit', edit_shopping_management_development_path(shopping_management_development) %></td>
        <td><%= link_to 'Destroy', shopping_management_development, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shopping management development', new_shopping_management_development_path %>

app/views/shopping_management_developments/menu.html.erb
<h1>購入商品在庫管理メニュー</h1>

<%= form_tag( { :action => 'new' } ) %>
<table width="80%" align="center">
  <tr>
    <td><%= submit_tag "購入商品登録" %></td>
  </tr>
  <tr><td></td></tr>

  <!-- 在庫検索用に変更予定 -->
  <tr>
    <td><%= submit_tag "在庫検索", {:type => "button", :onClick => "this.form.action='/shopping_management_developments/searchInit'; this.form.submit();"} %></td>
  </tr>
</table>

app/views/shopping_management_developments/new.html.erb
<h1>New shopping_management_development</h1>

<%= render 'form' %>

<%= link_to 'Back', shopping_management_developments_path %>

app/views/shopping_management_developments/search.html.erb
<html>
<head>
  <title>在庫検索</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <%= stylesheet_link_tag 'ror' %>
</head>

<body> 
<h2>在庫検索</h2>
カテゴリ または 商品名 のどちらかを選択して、検索してください。
<br>
<br>
<%= form_tag( { :action => 'search' } ) %>
  <!-- カテゴリ選択欄 @カテゴリTBL.カテゴリ名 -->
  カテゴリ <%= collection_select(:page, :categorycd, @category, :categorycd, :categoryname, :prompt => "選択してください") %>
           <!--                  out_object, out_column, object, in_column(cant see), in_column(output) -->
<br>
<br>
  <!-- 商品記入欄 -->
  商品名   <%= text_field_tag :goods, '', :size => 20 %>
<br>
<%= submit_tag "検索" %>
<br>
<%= form_tag( { :action => 'index' } ) %>
<%= submit_tag "メニューへ" %>
<br>
</body>
</html>

app/views/shopping_management_developments/searchResult.html.erb
<thead>
  <title>商品在庫一覧</title>
  <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
  <%= stylesheet_link_tag 'ror' %>
</thead>

<tbody>
<h2>商品在庫一覧</h2>
<table border="1">
  <tr style="background-color:pink">
    <th>カテゴリ</th>
    <th>商品名</th>
    <th>在庫数</th>
    <th>消費</th>
    <th>消費反映</th>
    <th>履歴</th>
  </tr>
  
  <% for r in @results %>
  <tr style="background-color:<%= cycle('white', 'yellow') %>">
      <td><%=h r.categoryCd %></td>
      <td><%=h r.goods %></td>
      <td><%=h r.zaiko %></td>
      <% form_tag() %>
      <td><%= number_field_tag :shohi , '', :size => 10 %></td>
      <td><%= button_to "反映" , { :action => 'createShohi' , :shohi => '1' , :category => r.categoryCd, :goods => r.goods } %><!-- submit_tag "反映",  { :type => "button", :onClick => "this.form.action='/shopping_management_developments/createShohi'; this.form.submit();"} --></td>
      <td><%= button_to "確認" , { :action => 'searchHistory', :category => r.categoryCd, :goods => r.goods }, :confirm => "履歴確認しますか?" %></td>
      <% end %>
  </tr>
</table>
<br><br>
<% form_tag({ :action => 'searchInit' }) %>
<!-- link_to '戻る', shopping_management_developments_searchInit_path -->
<%= button_to  "戻る" , { :action => 'searchInit' } %>
<br>
<%= link_to '購入商品在庫管理メニュー', root_path %>
</tbody>

app/views/shopping_management_developments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Categorycd:</strong>
  <%= @shopping_management_development.categoryCd %>
</p>

<p>
  <strong>Goods:</strong>
  <%= @shopping_management_development.goods %>
</p>

<p>
  <strong>Date:</strong>
  <%= @shopping_management_development.date %>
</p>

<p>
  <strong>Amount:</strong>
  <%= @shopping_management_development.amount %>
</p>

<p>
  <strong>Sum:</strong>
  <%= @shopping_management_development.sum %>
</p>

<p>
  <strong>Place:</strong>
  <%= @shopping_management_development.place %>
</p>

<%= link_to 'Edit', edit_shopping_management_development_path(@shopping_management_development) %> |
<%= link_to 'Back', shopping_management_developments_path %>